Hospital.Core/Models/Transacciones.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital.Core.Models
{
    public class Transacciones:BaseEntity
    {
        [Required]
        public string IdCajero { get; set; }
        [Required]
        public string IdPaciente { get; set; }
        [Required]
        [ForeignKey(nameof(TipoTransacciones))]
        public int TipoTransaccion { get; set; }
        [Required]
        [ForeignKey(nameof(EstadoTransacciones))]
        public int EstadoTransaccion { get; set; }
        [Required]
        public double Monto { get; set; }
        public DateTime Fecha { get; set; }
        //[Required]
        //[ForeignKey(nameof(Citas))]
        //public int IdCita { get; set; }
        public string Comentario { get; set; }

        #region Navigation Properties
        public virtual TipoTransaccion TipoTransacciones { get; set; }
        public virtual EstadoTransaccion EstadoTransacciones { get; set; }
        //public virtual Citas Citas { get; set; }


        #endregion
    }
}

Hospital.Core/Controllers/TransaccionesController.cs
using Hospital.Core.Context;
using Hospital.Core.Models;
using Hospital.Core.Models.SaveViewModel;
using Hospital.Core.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Serilog;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class TransaccionesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public TransaccionesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.TipoTransaccion = _context.TipoTransaccion.Select(e=> new SelectListItem 
            {
                Value= e.Id.ToString(),
                Text = e.Descripcion
            });
            ViewBag.EstadoTransaccion = _context.EstadoTransacciones.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            var pacientes = new List<SelectListItem>();
            var cajeros = new List<SelectListItem>();
            foreach (var user in _userManager.Users.ToList())
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    pacientes.Add(new SelectListItem 
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
                else if (await _userManager.IsInRoleAsync(user, SD.Role_Cajero))
                {
                    cajeros.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
            }
            ViewBag.Pacientes = pacientes;
            ViewBag.Cajeros = cajeros;

            //ViewBag.Citas = _context.Citas.Include(e=>e.Usuario).Include(e=>e.HorariosCitas).Select(e => new SelectListItem
            //{
            //    Value = e.Id.ToString(),
            //    Text = e.Usuario.Name +" "+e.Usuario.LastName+" | "+e.HorariosCitas.HoraInicio.ToString() + " - " + e.HorariosCitas.HoraFin.ToString()
            //});
            return View(new SaveTransaccionViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(SaveTransaccionViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _context.Transacciones.Add(new Models.Transacciones() 
                {
                    IdCajero = model.IdCajero,
                    IdPaciente = model.IdPaciente,
                    EstadoTransaccion = model.IdEstadoTransaccion,
                    TipoTransaccion = model.IdTipoTransaccion,
                    //IdCita = model.IdCita,
                    Monto = model.Monto,
                    Fecha = model.Fecha,
                    Comentario = model.Comentario??string.Empty,
                    Estado = true,
                });
                _context.SaveChanges();
                Log.Logger.Information("Transaccion creada");

                return RedirectToAction("Index");
            }
            ViewBag.TipoTransaccion = _context.TipoTransaccion.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            ViewBag.EstadoTransaccion = _context.EstadoTransacciones.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            var pacientes = new List<SelectListItem>();
            var cajeros = new List<SelectListItem>();
            foreach (var user in _userManager.Users.ToList())
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    pacientes.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
                else if (await _userManager.IsInRoleAsync(user, SD.Role_Cajero))
                {
                    cajeros.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
            }
            ViewBag.Pacientes = pacientes;
            ViewBag.Cajeros = cajeros;

            //ViewBag.Citas = _context.Citas.Include(e => e.Usuario).Include(e => e.HorariosCitas).Select(e => new SelectListItem
            //{
            //    Value = e.Id.ToString(),
            //    Text = e.Usuario.Name + " " + e.Usuario.LastName + " | " + e.HorariosCitas.HoraInicio.ToString() + " - " + e.HorariosCitas.HoraFin.ToString()
            //});
            return View(model);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var transaccion = _context.Transacciones.FirstOrDefault(t=>t.Id == id);
            if (transaccion == null) 
                return BadRequest();
            ViewBag.TipoTransaccion = _context.TipoTransaccion.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            ViewBag.EstadoTransaccion = _context.EstadoTransacciones.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            var pacientes = new List<SelectListItem>();
            var cajeros = new List<SelectListItem>();
            foreach (var user in _userManager.Users.ToList())
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    pacientes.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
                else if (await _userManager.IsInRoleAsync(user, SD.Role_Cajero))
                {
                    cajeros.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
            }
            ViewBag.Pacientes = pacientes;
            ViewBag.Cajeros = cajeros;

            //ViewBag.Citas = _context.Citas.Include(e => e.Usuario).Include(e => e.HorariosCitas).Select(e => new SelectListItem
            //{
            //    Value = e.Id.ToString(),
            //    Text = e.Usuario.Name + " " + e.Usuario.LastName + " | " + e.HorariosCitas.HoraInicio.ToString() + " - " + e.HorariosCitas.HoraFin.ToString()
            //});
            return View(
                new SaveTransaccionViewModel() {
                    Id =  transaccion.Id,
                    IdCajero = transaccion.IdCajero,
                    IdPaciente = transaccion.IdPaciente,
                    IdTipoTransaccion = transaccion.TipoTransaccion,
                    IdEstadoTransaccion = transaccion.EstadoTransaccion,
                    //IdCita = transaccion.IdCita,
                    Monto = transaccion.Monto,
                    Fecha = transaccion.Fecha,
                    Comentario = transaccion.Comentario??string.Empty,
                    Estado = transaccion.Estado
                });
        }
        [HttpPost]
        public async Task<IActionResult> Edit(SaveTransaccionViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Transacciones.Update(new Models.Transacciones()
                {
                    Id = model.Id,
                    IdCajero = model.IdCajero,
                    IdPaciente = model.IdPaciente,
                    EstadoTransaccion = model.IdEstadoTransaccion,
                    TipoTransaccion = model.IdTipoTransaccion,
                    //IdCita = model.IdCita,
                    Monto = model.Monto,
                    Fecha = model.Fecha,
                    Comentario = model.Comentario ?? string.Empty,
                    Estado = model.Estado,
                });
                _context.SaveChanges();
                Log.Logger.Information("Transaccion modificada");

                return RedirectToAction("Index");
            }
            ViewBag.TipoTransaccion = _context.TipoTransaccion.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            ViewBag.EstadoTransaccion = _context.EstadoTransacciones.Select(e => new SelectListItem
            {
                Value = e.Id.ToString(),
                Text = e.Descripcion
            });
            var pacientes = new List<SelectListItem>();
            var cajeros = new List<SelectListItem>();
            foreach (var user in _userManager.Users.ToList())
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    pacientes.Add(new SelectListItem
                    {
                        Value = user.Id,
                        Text = user.Name + " " + user.LastName
                    });
                }
                else if (await _userManager.IsInRoleAsync(user, SD.Role_Cajero))
                {
                    cajeros.Add(new SelectListItem
                    {
                        Value = user.Id,

Hospital.Core/Views/Transacciones/Create.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTransaccionViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="Transacciones" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Agregar transaccion
             </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for ="Id"/>
        <input type="hidden" asp-for ="Estado"/>
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="IdCajero">Cajero</label>
                @Html.DropDownListFor(m => m.IdCajero, (IEnumerable<SelectListItem>)ViewBag.Cajeros, "Elige el cajero", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdCajero" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdPaciente">Paciente</label>
                @Html.DropDownListFor(m => m.IdPaciente, (IEnumerable<SelectListItem>)ViewBag.Pacientes, "Elige el paciente", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdPaciente" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdTipoTransaccion">Tipo de transaccion</label>
                @Html.DropDownListFor(m => m.IdTipoTransaccion, (IEnumerable<SelectListItem>)ViewBag.TipoTransaccion, "Elige el tipo de transaccion", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdTipoTransaccion" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdEstadoTransaccion">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdEstadoTransaccion, (IEnumerable<SelectListItem>)ViewBag.EstadoTransaccion, "Elige el estado de la transasccion", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdEstadoTransaccion" class="text-danger"></span>
            </div>
            @* <div class="mb-3 col-lg-6">
                <label asp-for="IdCita">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdCita, (IEnumerable<SelectListItem>)ViewBag.Citas, "Elige la cita", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdCita" class="text-danger"></span>
            </div> *@
            <div class="mb-3 col-lg-6">
                <label asp-for="Monto">Monto</label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Fecha">Fecha</label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Comentario">Comentario</label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/Transacciones/Details.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTransaccionViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Detalles Transaccion
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="IdCajero">Cajero</label>
                @Html.DropDownListFor(m => m.IdCajero, (IEnumerable<SelectListItem>)ViewBag.Cajeros, "Elige el cajero", new { @class = "form-control", id = "roleSelect", @disabled = "disabled" })
                <span asp-validation-for="IdCajero" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdPaciente">Paciente</label>
                @Html.DropDownListFor(m => m.IdPaciente, (IEnumerable<SelectListItem>)ViewBag.Pacientes, "Elige el paciente", new { @class = "form-control", id = "roleSelect", @disabled = "disabled" })
                <span asp-validation-for="IdPaciente" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdTipoTransaccion">Tipo de transaccion</label>
                @Html.DropDownListFor(m => m.IdTipoTransaccion, (IEnumerable<SelectListItem>)ViewBag.TipoTransaccion, "Elige el tipo de transaccion", new { @class = "form-control", id = "roleSelect", @disabled = "disabled" })
                <span asp-validation-for="IdTipoTransaccion" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdEstadoTransaccion">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdEstadoTransaccion, (IEnumerable<SelectListItem>)ViewBag.EstadoTransaccion, "Elige el estado de la transasccion", new { @class = "form-control", id = "roleSelect", @disabled = "disabled" })
                <span asp-validation-for="IdEstadoTransaccion" class="text-danger"></span>
            </div>
            @* <div class="mb-3 col-lg-6">
                <label asp-for="IdCita">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdCita, (IEnumerable<SelectListItem>)ViewBag.Citas, "Elige la cita", new { @class = "form-control", id = "roleSelect", @disabled = "disabled" })
                <span asp-validation-for="IdCita" class="text-danger"></span>
            </div> *@
            <div class="mb-3 col-lg-6">
                <label asp-for="Monto">Monto</label>
                <input asp-for="Monto" class="form-control" disabled/>
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Fecha">Fecha</label>
                <input asp-for="Fecha" class="form-control" disabled/>
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Comentario">Comentario</label>
                <input asp-for="Comentario" class="form-control"  disabled/>
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
        </div>

        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/Transacciones/Edit.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTransaccionViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="Transacciones" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Editar Transaccion
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="IdCajero">Cajero</label>
                @Html.DropDownListFor(m => m.IdCajero, (IEnumerable<SelectListItem>)ViewBag.Cajeros, "Elige el cajero", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdCajero" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdPaciente">Paciente</label>
                @Html.DropDownListFor(m => m.IdPaciente, (IEnumerable<SelectListItem>)ViewBag.Pacientes, "Elige el paciente", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdPaciente" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdTipoTransaccion">Tipo de transaccion</label>
                @Html.DropDownListFor(m => m.IdTipoTransaccion, (IEnumerable<SelectListItem>)ViewBag.TipoTransaccion, "Elige el tipo de transaccion", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdTipoTransaccion" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="IdEstadoTransaccion">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdEstadoTransaccion, (IEnumerable<SelectListItem>)ViewBag.EstadoTransaccion, "Elige el estado de la transasccion", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdEstadoTransaccion" class="text-danger"></span>
            </div>
           @*  <div class="mb-3 col-lg-6">
                <label asp-for="IdCita">Estado de transaccion</label>
                @Html.DropDownListFor(m => m.IdCita, (IEnumerable<SelectListItem>)ViewBag.Citas, "Elige la cita", new { @class = "form-control", id = "roleSelect" })
                <span asp-validation-for="IdCita" class="text-danger"></span>
            </div> *@
            <div class="mb-3 col-lg-6">
                <label asp-for="Monto">Monto</label>
                <input asp-for="Monto" class="form-control" />
                <span asp-validation-for="Monto" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Fecha">Fecha</label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="Comentario">Comentario</label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/Transacciones/Index.cshtml
@{
    ViewData["Title"] = "Index";

}
<div class=" p-3">
    <div class="d-flex justify-content-between pt-4">
        <div class="p-2">
            <h2 class="text-primary">Mantenimiento Citas</h2>
        </div>
        <div class="p-2">
            <a style="text-decoration:none;" class="btn btn-info" asp-controller="Transacciones"
               asp-action="Create">
                Agregar Transaccion
            </a>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped " id="tblData" style="width:100%;">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Nombre Cajero
                </th>
                <th>
                    Nombre paciente
                </th>
                <th>
                    Tipo
                </th>
                <th>
                    Estado transaccion
                </th>
                <th>
                    Monto
                </th>
                <th>
                    Fecha
                </th>
                <th>
                    Estado
                </th>
                <th>
                    @*buttons*@
                </th>
            </tr>
        </thead>
    </table>
</div>
@section Scripts {
    <script src="~/js/Transaccion/Index.js"></script>
}