Hospital.Core/Models/HorariosCitas.cs
using System.ComponentModel.DataAnnotations;

namespace Hospital.Core.Models
{
    public class HorariosCitas:BaseEntity
    {
        [Required]
        public TimeSpan HoraInicio { get; set; }
        [Required]
        public TimeSpan HoraFin { get; set; }

        public virtual ICollection<Citas> Citas { get; set; }
    }
}

Hospital.Core/Controllers/HorariosCitasController.cs
using Hospital.Core.Context;
using Hospital.Core.Models.SaveViewModel;
using Hospital.Core.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class HorariosCitasController : Controller
    {
        private readonly ApplicationDbContext _context;
        public HorariosCitasController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new SaveHorarioCitaViewModel());
        }
        [HttpPost]
        public IActionResult Create(SaveHorarioCitaViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _context.HorariosCitas.Add(new Models.HorariosCitas() 
                {
                    HoraInicio = model.HoraInicio,
                    HoraFin = model.HoraFin,
                    Estado = true
                });
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            var area = _context.HorariosCitas.FirstOrDefault(a => a.Id == id);
            return View(new SaveHorarioCitaViewModel() {HoraInicio = area.HoraInicio, HoraFin= area.HoraFin,Id= area.Id,Estado = area.Estado });
        }
        [HttpPost]
        public IActionResult Edit(SaveHorarioCitaViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.HorariosCitas.Update(new Models.HorariosCitas()
                {
                    Id = model.Id,
                    HoraInicio = model.HoraInicio,
                    HoraFin = model.HoraFin,
                    Estado = true
                });
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        public async Task<IActionResult> ActivateDisactivate(int id)
        {
            var area = _context.HorariosCitas.AsNoTracking().FirstOrDefault(a => a.Id == id);
            area.Estado = !area.Estado;
             _context.HorariosCitas.Update(area);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var area = _context.HorariosCitas.FirstOrDefault(a => a.Id == id);
            return View(new SaveHorarioCitaViewModel() { HoraInicio = area.HoraInicio, HoraFin = area.HoraFin, Id = area.Id, Estado = area.Estado });
        }
        public JsonResult GetAll()
        {
            var listHorarios = new List<HorarioCitaViewModel>();

            foreach (var horario in _context.HorariosCitas)
            {
                listHorarios.Add(new HorarioCitaViewModel 
                {
                    Id = horario.Id,
                    HoraInicio = horario.HoraInicio,
                    HoraFin = horario.HoraFin,
                    Estado = horario.Estado
                });
            }
            return Json( new { data= listHorarios });
        }

    }
}

Hospital.Core/Views/HorariosCitas/Create.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveHorarioCitaViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="HorariosCitas" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Agregar horario
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraInicio">Hora Inicio</label>
                <input asp-for="HoraInicio" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraFin">Hora Fin</label>
                <input asp-for="HoraFin" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/HorariosCitas/Details.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveHorarioCitaViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Detils horario
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraInicio">Hora Inicio</label>
                <input asp-for="HoraInicio" class="form-control" disabled/>
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraFin">Hora Fin</label>
                <input asp-for="HoraFin" class="form-control" disabled/>
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
        </div>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/HorariosCitas/Edit.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveHorarioCitaViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="HorariosCitas" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Editar horario
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraInicio">Hora Inicio</label>
                <input asp-for="HoraInicio" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
            <div class="mb-3 col-lg-6">
                <label asp-for="HoraFin">Hora Fin</label>
                <input asp-for="HoraFin" class="form-control" />
                <span asp-validation-for="HoraInicio" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/HorariosCitas/Index.cshtml
@{
    ViewData["Title"] = "Index";

}
<div class=" p-3">
    <div class="d-flex justify-content-between pt-4">
        <div class="p-2">
            <h2 class="text-primary">Mantenimiento Horarios Citas</h2>
        </div>
        <div class="p-2">
            <a style="text-decoration:none;" class="btn btn-info" asp-controller="HorariosCitas"
               asp-action="Create">
                Agregar Horario
            </a>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped " id="tblData" style="width:100%;">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Hora Inicio
                </th>
                <th>
                    Hora Fin
                </th>
                <th>
                    Estado
                </th>
                <th>
                    @*buttons*@
                </th>
            </tr>
        </thead>
    </table>
</div>
@section Scripts {
    <script src="~/js/HorariosCitas/Index.js"></script>
}