Hospital.Core/Controllers/CitasController.cs
using Hospital.Core.Context;
using Hospital.Core.Models;
using Hospital.Core.Models.SaveViewModel;
using Hospital.Core.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class CitasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public CitasController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index( )
        {
            return View();
        }
        public async Task<IActionResult> Create()
        {
            var userInRole = new List<ApplicationUser>();
            var users = _userManager.Users.ToList();
            foreach(var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    userInRole.Add(user);
                }
            }
            ViewBag.Users = userInRole.Select(u => new SelectListItem 
            {
                Value = u.Id,
                Text = u.Name + " " + u.LastName
            }).ToList();

            ViewBag.Servicios = _context.Servicios.Include(s=>s.TipoServicio).Include(s=>s.AreasMedicas).Select( s=> new SelectListItem 
            {
                Value = s.Id.ToString(),
                Text = s.TipoServicio.Descripcion+", "+ s.AreasMedicas.Descripcion

            }).ToList();
            ViewBag.Horarios = _context.HorariosCitas.Select(s => new SelectListItem 
            {
                Value = s.Id.ToString(),
                Text = s.HoraInicio.ToString() + " - "+s.HoraFin.ToString()
            });
            return View(new SaveCitaViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(SaveCitaViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _context.Citas.Add(new Citas() 
                {
                    IdPaciente = model.IdPaciente,
                    IdServicio = model.IdServicio,
                    FechaAgendada = model.FechaAgendada,
                    Estado = true,
                    idHorarioCita = model.idHorarioCita
                });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            var userInRole = new List<ApplicationUser>();
            var users = _userManager.Users.ToList();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    userInRole.Add(user);
                }
            }
            ViewBag.Users = userInRole.Select(u => new SelectListItem
            {
                Value = u.Id,
                Text = u.Name + " " + u.LastName
            }).ToList();

            ViewBag.Servicios = _context.Servicios.Include(s => s.TipoServicio).Include(s => s.AreasMedicas).Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = s.TipoServicio.Descripcion + ", " + s.AreasMedicas.Descripcion

            }).ToList();
            ViewBag.Horarios = _context.HorariosCitas.Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = s.HoraInicio.ToString() + " - " + s.HoraFin.ToString()
            });
            return View(model);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var cita = _context.Citas.FirstOrDefault(c => c.Id == id);
            var userInRole = new List<ApplicationUser>();
            var users = _userManager.Users.ToList();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    userInRole.Add(user);
                }
            }
            ViewBag.Users = userInRole.Select(u => new SelectListItem
            {
                Selected = u.Id == cita.IdPaciente,
                Value = u.Id,
                Text = u.Name + " " + u.LastName
            }).ToList();

            ViewBag.Servicios = _context.Servicios.Include(s => s.TipoServicio).Include(s => s.AreasMedicas).Select(s => new SelectListItem
            {
                Selected = s.Id == cita.IdServicio,
                Value = s.Id.ToString(),
                Text = s.TipoServicio.Descripcion + ", " + s.AreasMedicas.Descripcion

            }).ToList();
            ViewBag.Horarios = _context.HorariosCitas.Select(s => new SelectListItem
            {
                Selected = s.Id == cita.idHorarioCita,
                Value = s.Id.ToString(),
                Text = s.HoraInicio.ToString() + " - " + s.HoraFin.ToString()
            });
            return View(new SaveCitaViewModel()
            {
                Id = cita.Id,
                IdPaciente = cita.IdPaciente,
                IdServicio = cita.IdServicio,
                FechaAgendada = cita.FechaAgendada,
                Estado = cita.Estado,
                idHorarioCita = cita.idHorarioCita
            });
        }
        [HttpPost]
        public async Task<IActionResult> Edit(SaveCitaViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.Citas.Update(new Citas()
                {
                    Id = model.Id,
                    IdPaciente = model.IdPaciente,
                    IdServicio = model.IdServicio,
                    FechaAgendada = model.FechaAgendada,
                    Estado = true,
                    idHorarioCita = model.idHorarioCita
                });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            var userInRole = new List<ApplicationUser>();
            var users = _userManager.Users.ToList();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    userInRole.Add(user);
                }
            }
            ViewBag.Users = userInRole.Select(u => new SelectListItem
            {
                Value = u.Id,
                Text = u.Name + " " + u.LastName
            }).ToList();
            ViewBag.Horarios = _context.HorariosCitas.Select(s => new SelectListItem
            {
                Selected = s.Id == model.idHorarioCita,
                Value = s.Id.ToString(),
                Text = s.HoraInicio.ToString() + " - " + s.HoraFin.ToString()
            });
            ViewBag.Servicios = _context.Servicios.Include(s => s.TipoServicio).Include(s => s.AreasMedicas).Select(s => new SelectListItem
            {
                Value = s.Id.ToString(),
                Text = s.TipoServicio.Descripcion + ", " + s.AreasMedicas.Descripcion

            }).ToList();
            return View(new SaveCitaViewModel());
        }
        public async Task<IActionResult> Details(int id)
        {
            var cita = _context.Citas.FirstOrDefault(c => c.Id == id);
            var userInRole = new List<ApplicationUser>();
            var users = _userManager.Users.ToList();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, SD.Role_Usuairo))
                {
                    userInRole.Add(user);
                }
            }
            ViewBag.Users = userInRole.Select(u => new SelectListItem
            {
                Selected = u.Id == cita.IdPaciente,
                Value = u.Id,
                Text = u.Name + " " + u.LastName
            }).ToList();

            ViewBag.Servicios = _context.Servicios.Include(s => s.TipoServicio).Include(s => s.AreasMedicas).Select(s => new SelectListItem
            {
                Selected = s.Id == cita.IdServicio,
                Value = s.Id.ToString(),
                Text = s.TipoServicio.Descripcion + ", " + s.AreasMedicas.Descripcion

            }).ToList();
            return View(new SaveCitaViewModel()
            {
                Id = cita.Id,
                IdPaciente = cita.IdPaciente,
                IdServicio = cita.IdServicio,
                FechaAgendada = cita.FechaAgendada,
                Estado = cita.Estado,
                idHorarioCita = cita.idHorarioCita
            });
        }
        public IActionResult ActivateDisactivate(int id)
        {
            var cita = _context.Citas.AsNoTracking().FirstOrDefault(c=>c.Id == id);
            cita.Estado = !cita.Estado;
            _context.Citas.Update(cita);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult GetAll()
        {
            var listCitas = new List<CitaViewModel>();
            foreach (var cita in _context.Citas.Include(e=>e.Usuario).Include(e=>e.Servicios).Include(e=>e.HorariosCitas))
            {
                var preCita = new CitaViewModel()
                {
                    Id = cita.Id,
                    NombrePaciente = cita.Usuario.Name + " " + cita.Usuario.LastName,
                    FechaAgendada = cita.FechaAgendada,
                    Estado = cita.Estado,
                    HorarioCita = cita.HorariosCitas.HoraInicio.ToString()+" - "+ cita.HorariosCitas.HoraFin.ToString()
                };
                preCita.NombreServicio = _context.Servicios.Include(e => e.TipoServicio).Where(s=>s.Id == cita.IdServicio).FirstOrDefault().TipoServicio.Descripcion;

Hospital.Core/Controllers/HomeController.cs
using Hospital.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hospital.Core/Controllers/ServiciosController.cs
using Hospital.Core.Context;
using Hospital.Core.Models.SaveViewModel;
using Hospital.Core.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class ServiciosController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ServiciosController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            var areasMedicas = _context.AreasMedicas.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.areasMedicas = areasMedicas;

            var tipoServicio = _context.TipoServicio.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.tipoServicio = tipoServicio;
            return View(new SaveServicioViewModel());
        }
        [HttpPost]
        public IActionResult Create(SaveServicioViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _context.Servicios.Add(new Models.Servicios() 
                {
                    IdAreaMedica = model.IdAreaMedica,
                    IdTipoServicio = model.IdTipoServico,
                    Costo = model.Costo,
                    Estado = true
                });
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            var areasMedicas = _context.AreasMedicas.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.areasMedicas = areasMedicas;

            var tipoServicio = _context.TipoServicio.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.tipoServicio = tipoServicio;
            return View(model);
        }
        public IActionResult Edit(int id) 
        {
            var servicio = _context.Servicios.FirstOrDefault(s => s.Id == id);
            var areasMedicas = _context.AreasMedicas.Select(r => new SelectListItem
            {
                Selected = servicio.IdAreaMedica == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.areasMedicas = areasMedicas;

            var tipoServicio = _context.TipoServicio.Select(r => new SelectListItem
            {
                Selected = servicio.IdTipoServicio == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.tipoServicio = tipoServicio;

            return View(new SaveServicioViewModel() 
            {
                Id = id,
                Estado = servicio.Estado,
                Costo = servicio.Costo,
                IdAreaMedica= servicio.IdAreaMedica,
                IdTipoServico = servicio.IdTipoServicio});
        }
        [HttpPost]
        public IActionResult Edit(SaveServicioViewModel model)
        {
            var servicio = _context.Servicios.AsNoTracking().FirstOrDefault(s => s.Id == model.Id);

            if (ModelState.IsValid)
            {
                servicio.Costo = model.Costo;
                servicio.IdAreaMedica = model.IdAreaMedica;
                servicio.IdTipoServicio = model.IdTipoServico;
                _context.Servicios.Update(servicio);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            var areasMedicas = _context.AreasMedicas.Select(r => new SelectListItem
            {
                Selected = servicio.IdAreaMedica == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.areasMedicas = areasMedicas;

            var tipoServicio = _context.TipoServicio.Select(r => new SelectListItem
            {
                Selected = servicio.IdTipoServicio == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();
            ViewBag.tipoServicio = tipoServicio;
            return View(model);
        }
        public IActionResult Details(int id)
        {
            var servicio = _context.Servicios.FirstOrDefault(s => s.Id == id);
            var areasMedicas = _context.AreasMedicas.Select(r => new SelectListItem
            {
                Selected = servicio.IdAreaMedica == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.areasMedicas = areasMedicas;

            var tipoServicio = _context.TipoServicio.Select(r => new SelectListItem
            {
                Selected = servicio.IdTipoServicio == r.Id,
                Value = r.Id.ToString(),
                Text = r.Descripcion
            }).ToList();

            ViewBag.tipoServicio = tipoServicio;

            return View(new SaveServicioViewModel()
            {
                Id = id,
                Estado = servicio.Estado,
                Costo = servicio.Costo,
                IdAreaMedica = servicio.IdAreaMedica,
                IdTipoServico = servicio.IdTipoServicio
            });
        }
        public async Task<IActionResult> ActivateDisactivate(int id)
        { 
            var servcio = _context.Servicios.AsNoTracking().FirstOrDefault(s=>s.Id == id);
            servcio.Estado = !servcio.Estado;
            _context.Servicios.Update(servcio);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public JsonResult GetAll()
        {
            var listServicios = new List<ServicioViewModel>();
            foreach (var servicio in _context.Servicios.Include(e=>e.AreasMedicas).Include(e=>e.TipoServicio))
            {
                listServicios.Add(new ServicioViewModel
                {
                    Id = servicio.Id,
                    IdAreaMedica = servicio.IdAreaMedica,
                    IdTipoServico = servicio.IdTipoServicio,
                    Costo = servicio.Costo,
                    Estado = servicio.Estado,
                    DescricionTipoServcio = servicio.TipoServicio.Descripcion,
                    DescripcionAreaMedica = servicio.AreasMedicas.Descripcion
                });

            }
            return Json(new { data = listServicios });
        }
    }
}

Hospital.Core/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1>Mantenimiento</h1>
</div>
<div class="row">
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="User" asp-action="Index" >
                <div class="content-box color-effect-1">
                    <h3>Usarios</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-user"></i>
                            </div>
                    </div>

                    <p>Registrar y modificar usuarios.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="Citas" asp-action="Index" >
                <div class="content-box color-effect-1">
                    <h3>Citas</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-regular fa-calendar-check"></i>
                            </div>
                    </div>

                    <p>Ver el registro de citas.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="Transacciones" asp-action="Index">
                <div class="content-box color-effect-1">
                    <h3>Transacciones</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-dollar-sign"></i>
                         </div>
                    </div>

                    <p>Ver el estados de las transacciones.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="Servicios" asp-action="Index">
                <div class="content-box color-effect-1">
                    <h3>Servicios</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-heart"></i>
                            </div>
                    </div>

                    <p>Agregar y editar servicios.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="TiposServicios" asp-action="Index">
                <div class="content-box color-effect-1">
                    <h3>Tipos Servicios</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-dollar-sign"></i>
                        </div>
                    </div>

                    <p>Agregar y editar tipos de servicios.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="AreasMedicas" asp-action="Index">
                <div class="content-box color-effect-1">
                    <h3>Areas medicas</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-dollar-sign"></i>
                            </div>

                    </div>

                    <p>Agregar y editar areas medicas.</p>
                </div>
            </a>
        </div>
    </div>
    <div class="col-md-4 col-lg-3">
        <div class="four columns">
            <a asp-controller="HorariosCitas" asp-action="Index">
                <div class="content-box color-effect-1">
                    <h3>Horario Citas</h3>

                    <div class="box-icon-wrap box-icon-effect-1 box-icon-effect-1a">
                        <div class="box-icon">
                            <i class="fa-solid fa-dollar-sign"></i>
                        </div>

                    </div>

                    <p>Agregar y editar horarios para citas.</p>
                </div>
            </a>
        </div>
    <style>
        .container {
            margin-top: 100px;
        }

        .content-box {
            padding: 32px 28px;
            margin: 0 0 20px;
            text-align: center;
            cursor: pointer
        }



            .content-box p {
                margin: 1px;
                color: #fff
            }

            .content-box h3 {
                line-height: 26px;
                padding-bottom: 8px;
                color: #fff;
                font-weight: 600
            }

            .content-box i {
                font-size: 80px;
                height: 80px;
                color: #fff;
                margin: 10px 0;
                display: block
            }

            .content-box.color-effect-1 {
                background: #38c782
            }




        .box-icon i {
            display: inline-block;
            font-size: 0;
            cursor: pointer;
            margin: 15px 0;
            width: 90px;
            height: 90px;
            border-radius: 50%;
            text-align: center;
            position: relative;
            z-index: 1;
            color: #fff
        }

            .box-icon i:after {
                pointer-events: none;
                position: absolute;
                width: 100%;
                height: 100%;
                border-radius: 50%;
                content: '';
                -webkit-box-sizing: content-box;
                -moz-box-sizing: content-box;
                box-sizing: content-box
            }

            .box-icon i:before {
                speak: none;
                font-size: 40px;
                line-height: 90px;
                font-style: normal;
                font-weight: 400;
                font-variant: normal;
                text-transform: none;
                display: block;
                -webkit-font-smoothing: antialiased
            }

        .box-icon-effect-1 .box-icon i {
            background: rgba(255, 255, 255, .2);
            color: #fff;
            -webkit-transition: background .2s, color .2s;
            -moz-transition: background .2s, color .2s;
            transition: background .2s, color .2s
        }

            .box-icon-effect-1 .box-icon i:after {
                top: -7px;
                left: -7px;
                padding: 7px;
                box-shadow: 0 0 0 4px #fff;
                -webkit-transition: -webkit-transform .2s, opacity .2s;
                -webkit-transform: scale(.8);
                -moz-transition: -moz-transform .2s, opacity .2s;
                -moz-transform: scale(.8);
                -ms-transform: scale(.8);
                transition: transform .2s, opacity .2s;
                transform: scale(.8);
                opacity: 0
            }

        .content-box:hover .box-icon-effect-1a .box-icon i {
            background: #fff;
            color: #3acf87
        }

            .content-box:hover .box-icon-effect-1a .box-icon i:after {
                -webkit-transform: scale(1);
                -moz-transform: scale(1);
                -ms-transform: scale(1);
                transform: scale(1);
                opacity: 1
            }

        .box-icon-effect-2 .box-icon i {
            box-shadow: 0 0 0 4px #fff;
            overflow: hidden;
            -webkit-transition: background .3s, color .3s, box-shadow .3s;
            -moz-transition: background .3s, color .3s, box-shadow .3s;
            transition: background .3s, color .3s, box-shadow .3s;
            color: #fff
        }

        a:link {
            text-decoration: none;
        }
    </style>


</div>