Hospital.Core/Controllers/TiposServiciosController.cs
using Hospital.Core.Context;
using Hospital.Core.Models.SaveViewModel;
using Hospital.Core.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Core.Controllers
{
    [Authorize]
    public class TiposServiciosController : Controller
    {
        private readonly ApplicationDbContext _context;
        public TiposServiciosController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new SaveTipoServicioViewModel());
        }
        [HttpPost]
        public IActionResult Create(SaveTipoServicioViewModel model)
        {
            if (ModelState.IsValid) 
            {
                _context.TipoServicio.Add(new Models.TipoServicio() 
                {
                    Descripcion = model.Descripcion,
                    Estado = true
                });
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int id)
        {
            var tipoServ = _context.TipoServicio.FirstOrDefault(a => a.Id == id);
            return View(new SaveTipoServicioViewModel() {Descripcion = tipoServ.Descripcion,Id= tipoServ.Id,Estado = tipoServ.Estado });
        }
        [HttpPost]
        public IActionResult Edit(SaveTipoServicioViewModel model)
        {
            if (ModelState.IsValid)
            {
                _context.TipoServicio.Update(new Models.TipoServicio()
                {
                    Id = model.Id,
                    Descripcion = model.Descripcion,
                    Estado = model.Estado
                });
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize]
        public async Task<IActionResult> ActivateDisactivate(int id)
        {
            var tipoServ = _context.TipoServicio.AsNoTracking().FirstOrDefault(a => a.Id == id);
            tipoServ.Estado = !tipoServ.Estado;
             _context.TipoServicio.Update(tipoServ);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var tipoServ = _context.TipoServicio.FirstOrDefault(a => a.Id == id);
            return View(new SaveTipoServicioViewModel() { Descripcion = tipoServ.Descripcion, Id = tipoServ.Id, Estado = tipoServ.Estado });
        }
        public JsonResult GetAll()
        {
            var listTipoServ = new List<TipoServicioViewModel>();

            foreach (var area in _context.TipoServicio)
            {
                listTipoServ.Add(new TipoServicioViewModel 
                {
                    Id = area.Id,
                    Descripcion= area.Descripcion,
                    Estado= area.Estado,
                });
            }
            return Json( new { data= listTipoServ });
        }

    }
}

Hospital.Core/Views/TiposServicios/Create.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTipoServicioViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="TiposServicios" asp-action="Create">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Agregar tipo servicio
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for ="Id"/>
        <input type="hidden" asp-for ="Estado"/>
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="Descripcion">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/TiposServicios/Details.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTipoServicioViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form>
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Detalles tipo servicio
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="Descripcion">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" disabled/>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>

        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/TiposServicios/Edit.cshtml
@model Hospital.Core.Models.SaveViewModel.SaveTipoServicioViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="post" asp-controller="TiposServicios" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">
                Editar tipo servicio
            </h2>
            <hr />
        </div>
        @* <div asp-validation-summary="All" class="alert alert-danger" ></div> *@
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Estado" />
        <div class="row">
            <div class="mb-3 col-lg-6">
                <label asp-for="Descripcion">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
        <a asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to list
        </a>
    </div>
</form>

Hospital.Core/Views/TiposServicios/Index.cshtml
@{
    ViewData["Title"] = "Index";

}
<div class=" p-3">
    <div class="d-flex justify-content-between pt-4">
        <div class="p-2">
            <h2 class="text-primary">Mantenimiento Tipos Servicios</h2>
        </div>
        <div class="p-2">
            <a style="text-decoration:none;" class="btn btn-info" asp-controller="TiposServicios"
               asp-action="Create">
                Agregar Tipo Servicio
            </a>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped " id="tblData" style="width:100%;">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Descripcion
                </th>
                <th>
                    Estado
                </th>
                <th>
                    @*buttons*@
                </th>
            </tr>
        </thead>
    </table>
</div>
@section Scripts {
    <script src="~/js/TiposServicios/Index.js"></script>
}